name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    environement: googleClub
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build \
            --build-arg APP_PORT=${{ secrets.APP_PORT }} \
            --build-arg DB_URL=${{ secrets.DB_URL }} \
            --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg OWNER_USERNAME=${{ secrets.OWNER_USERNAME }} \
            --build-arg OWNER_PASSWORD=${{ secrets.OWNER_PASSWORD }} \
            --build-arg CLUB_MAIL=${{ secrets.CLUB_MAIL }} \
            --build-arg CLUB_PASSWORD=${{ secrets.CLUB_PASSWORD }} \
            --build-arg HASH_KEY=${{ secrets.HASH_KEY }} \
            -t ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:latest .
          docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:latest
