<<<<<<< HEAD
name: Build and Deploy Application via FTPS - googleBack
=======
name: Build and Deploy Docker Image to Azure Web App - googleBack
>>>>>>> 4e9e5cc1f8fe237916a1e13f4e1bc87d4d57823e

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 

    environment: googleClub

    env:
      SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILES_ACTIVE }}
      DB_SERVER_NAME: ${{ secrets.DB_SERVER_NAME }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      OWNER_USERNAME: ${{ secrets.OWNER_USERNAME }}
      OWNER_PASSWORD: ${{ secrets.OWNER_PASSWORD }}
      CLUB_MAIL: ${{ secrets.CLUB_MAIL }}
      CLUB_PASSWORD: ${{ secrets.CLUB_PASSWORD }}
      HASH_KEY: ${{ secrets.HASH_KEY }}
      AZURE_APP_NAME: googleBack

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'  

      - name: Build with Maven
        run: mvn clean package -DskipTests

<<<<<<< HEAD
      - name: Upload JAR File
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/auth-0.0.1-SNAPSHOT.jar
=======
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest \
            --build-arg JAR_FILE=target/*.jar .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
>>>>>>> 4e9e5cc1f8fe237916a1e13f4e1bc87d4d57823e

  deploy:
    runs-on: ubuntu-latest
    needs: build
<<<<<<< HEAD
    steps:
      - name: Download JAR File
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Install FTP Client
        run: sudo apt-get install -y lftp

      - name: Deploy to Azure Web App via FTPS
        env:
          FTPS_SERVER: ${{ secrets.FTPS_SERVER }}
          FTPS_USERNAME: ${{ secrets.FTPS_USERNAME }}
          FTPS_PASSWORD: ${{ secrets.FTPS_PASSWORD }}
        run: |
          lftp -f "
          open ftps://$FTPS_SERVER
          user $FTPS_USERNAME $FTPS_PASSWORD
          mirror -R ./target /site/wwwroot
          bye
          "
=======
    environment:
      name: 'googleClub'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write 

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

          
      - name: Deploy Docker image to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'googleBack'
          slot-name: 'googleClub'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.DOCKER_USERNAME }}/myapp:latest  
>>>>>>> 4e9e5cc1f8fe237916a1e13f4e1bc87d4d57823e
