name: Build and Deploy JAR to Azure Web App via FTPS - googleBack

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: googleClub

    env:
      SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILES_ACTIVE }}
      DB_SERVER_NAME: ${{ secrets.DB_SERVER_NAME }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      OWNER_USERNAME: ${{ secrets.OWNER_USERNAME }}
      OWNER_PASSWORD: ${{ secrets.OWNER_PASSWORD }}
      CLUB_MAIL: ${{ secrets.CLUB_MAIL }}
      CLUB_PASSWORD: ${{ secrets.CLUB_PASSWORD }}
      HASH_KEY: ${{ secrets.HASH_KEY }}
      AZURE_APP_NAME: googleBack

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Verify JAR file in the target directory
        run: |
          # Check if the JAR file was built correctly
          ls -l target/
          
          # Fail the job if the JAR file is not present
          if [ ! -f "target/auth-0.0.1-SNAPSHOT.jar" ]; then
            echo "JAR file not found!"
            exit 1
          fi

      - name: Upload JAR File as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/auth-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download JAR File from Build
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: ./ # Download directly to the current directory

      - name: List Downloaded Files for Debugging
        run: ls -l

      - name: Install lftp Client
        run: sudo apt-get install -y lftp

      - name: Deploy to Azure Web App via FTPS
        env:
          FTPS_SERVER: ${{ secrets.FTPS_SERVER }}
          FTPS_USERNAME: ${{ secrets.FTPS_USERNAME }}
          FTPS_PASSWORD: ${{ secrets.FTPS_PASSWORD }}
        run: |
          # Check if the JAR file exists locally
          if [ ! -f "./auth-0.0.1-SNAPSHOT.jar" ]; then
            echo "JAR file not found!"
            exit 1
          fi
          
          # Connect to FTPS and upload the JAR file
          lftp -f "
          open ftps://$FTPS_SERVER
          user $FTPS_USERNAME $FTPS_PASSWORD
          # Make sure the target directory exists
          mkdir -p /site/wwwroot
          # Upload the JAR file
          put ./auth-0.0.1-SNAPSHOT.jar -o /site/wwwroot/auth-0.0.1-SNAPSHOT.jar
          bye
          "
